package org.acme.recommendation_rules;

import org.acme.cloud_solution_projects.Project;
import org.acme.cloud_solution_projects.CloudSolution;
import org.acme.cloud_solution_projects.ViewRecommendation;

rule "view-test"

    ruleflow-group "view-rules"
    no-loop true

    when
        $project : Project(title != null)
    then
        System.out.println("found project with no cloud solution");
        //actions
        ViewRecommendation view = new ViewRecommendation();
		view.setViewName( "projects/" + project.id + "/cloud" );
		insert( view );

end
