package org.acme.recommendation_rules;

import org.acme.cloud_solution_projects.Project;
import org.acme.cloud_solution_projects.CloudSolution;
import org.acme.cloud_solution_projects.ViewRecommendation;

rule "TestProject"

    ruleflow-group "view-rules"

    when
        $project : Project()
    then
        System.out.println("found project with no cloud solution");
        //actions
        modify($view) {setViewName("test from rule")};

end
