package org.acme.cloud_solution_projects;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class CloudSolution implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "CLOUDSOLUTION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "CLOUDSOLUTION_ID_SEQ", name = "CLOUDSOLUTION_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Cloud Provider")
   private java.lang.String cloudProvider;

   @org.kie.api.definition.type.Label(value = "Location Country")
   private java.lang.String locationCountry;

   @org.kie.api.definition.type.Label(value = "Has Data Visualization")
   private java.lang.Boolean hasDataVisualization;

   @org.kie.api.definition.type.Label(value = "Has Data Ingestion")
   private java.lang.Boolean hasDataIngestion;

   public CloudSolution()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.String getCloudProvider()
   {
      return this.cloudProvider;
   }

   public void setCloudProvider(java.lang.String cloudProvider)
   {
      this.cloudProvider = cloudProvider;
   }

   public java.lang.String getLocationCountry()
   {
      return this.locationCountry;
   }

   public void setLocationCountry(java.lang.String locationCountry)
   {
      this.locationCountry = locationCountry;
   }

   public java.lang.Boolean getHasDataVisualization()
   {
      return this.hasDataVisualization;
   }

   public void setHasDataVisualization(java.lang.Boolean hasDataVisualization)
   {
      this.hasDataVisualization = hasDataVisualization;
   }

   public java.lang.Boolean getHasDataIngestion()
   {
      return this.hasDataIngestion;
   }

   public void setHasDataIngestion(java.lang.Boolean hasDataIngestion)
   {
      this.hasDataIngestion = hasDataIngestion;
   }

   public CloudSolution(java.lang.Long id, java.lang.String cloudProvider,
         java.lang.String locationCountry,
         java.lang.Boolean hasDataVisualization,
         java.lang.Boolean hasDataIngestion)
   {
      this.id = id;
      this.cloudProvider = cloudProvider;
      this.locationCountry = locationCountry;
      this.hasDataVisualization = hasDataVisualization;
      this.hasDataIngestion = hasDataIngestion;
   }

}