package org.acme.cloud_solution_projects;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class DataIngestion implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "DATAINGESTION_ID_GENERATOR")
   @javax.persistence.Id
   @javax.persistence.SequenceGenerator(sequenceName = "DATAINGESTION_ID_SEQ", name = "DATAINGESTION_ID_GENERATOR")
   private java.lang.Long id;

   @org.kie.api.definition.type.Label(value = "Requires License")
   private java.lang.Boolean requiresLicense;

   @org.kie.api.definition.type.Label(value = "License Number")
   private java.lang.String licenseNumber;

   @org.kie.api.definition.type.Label(value = "ETL Tool preference")
   private java.lang.String etlToolPreference;

   @org.kie.api.definition.type.Label(value = "Number for Developers")
   private java.lang.Integer developersQuantity;

   public DataIngestion()
   {
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public java.lang.Boolean getRequiresLicense()
   {
      return this.requiresLicense;
   }

   public void setRequiresLicense(java.lang.Boolean requiresLicense)
   {
      this.requiresLicense = requiresLicense;
   }

   public java.lang.String getLicenseNumber()
   {
      return this.licenseNumber;
   }

   public void setLicenseNumber(java.lang.String licenseNumber)
   {
      this.licenseNumber = licenseNumber;
   }

   public java.lang.String getEtlToolPreference()
   {
      return this.etlToolPreference;
   }

   public void setEtlToolPreference(java.lang.String etlToolPreference)
   {
      this.etlToolPreference = etlToolPreference;
   }

   public java.lang.Integer getDevelopersQuantity()
   {
      return this.developersQuantity;
   }

   public void setDevelopersQuantity(java.lang.Integer developersQuantity)
   {
      this.developersQuantity = developersQuantity;
   }

   public DataIngestion(java.lang.Long id, java.lang.Boolean requiresLicense,
         java.lang.String licenseNumber, java.lang.String etlToolPreference,
         java.lang.Integer developersQuantity)
   {
      this.id = id;
      this.requiresLicense = requiresLicense;
      this.licenseNumber = licenseNumber;
      this.etlToolPreference = etlToolPreference;
      this.developersQuantity = developersQuantity;
   }

}