package org.acme.cloud_solution_projects;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ViewRecommendation implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String viewName;
	private String recommendation;

	public ViewRecommendation() {
	}

	public java.lang.String getViewName() {
		return this.viewName;
	}

	public void setViewName(java.lang.String viewName) {
		this.viewName = viewName;
	}

	public java.lang.String getRecommendation() {
		return this.recommendation;
	}

	public void setRecommendation(java.lang.String recommendation) {
		this.recommendation = recommendation;
	}

	public ViewRecommendation(java.lang.String viewName, java.lang.String recommendation) {
		this.viewName = viewName;
		this.recommendation = recommendation;
	}

	@Override
	public String toString() {
		return "ViewRecommendation [viewName=" + viewName + ", recommendation=" + recommendation + "]";
	}

}